//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЛР15
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public byte id_gr { get; set; }
        public string nazv_gr { get; set; }
        public Nullable<int> count { get; set; }
    }
}
