//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЛР15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ip521_SegaAndGeraEntities : DbContext
    {
        public Ip521_SegaAndGeraEntities()
            : base("name=Ip521_SegaAndGeraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<uspev> uspev { get; set; }
        public virtual DbSet<Абитуриенты> Абитуриенты { get; set; }
        public virtual DbSet<Дисциплины> Дисциплины { get; set; }
        public virtual DbSet<Журнал> Журнал { get; set; }
        public virtual DbSet<Заявления> Заявления { get; set; }
        public virtual DbSet<Оценки> Оценки { get; set; }
        public virtual DbSet<Специальности> Специальности { get; set; }
        public virtual DbSet<Экзамены> Экзамены { get; set; }
    }
}
